### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by UlrichThiess** [ITSpecialist111/ai_automation_suggester#44]
Where exact could i set
```
4. (Optional) Custom Prompt:
   Add a custom system prompt during integration setup or when triggering services.
```
Because i want german language. :-)

Thanks.

**Comment by ITSpecialist111** [comment]
Hey 👋  Thanks for investigating this. You can type any language into the custom prompt, or adjust the internal system prompt. There's a DE language set for UI translation also. Unless you mean something totally different

**Comment by UlrichThiess** [comment]
I only see this during setup:
![grafik](https://github.com/user-attachments/assets/7cdbf2c8-a5a9-4ebb-8880-85579b20cc19)

I could not find where to setup the custom prompt.

I found that i could enter a custom prompt if i setup an automation, but as default?

**Comment by ITSpecialist111** [comment]
Oh I see! You're in the wrong place ;) Head to Dev Tools, -> Actions.

[Image]



________________________________

**Comment by UlrichThiess** [comment]
Ah, ok, i see. But is there any way to set up a prompt as default? Maybe it is an good idea to setup a prompt in the setup?

**Comment by ITSpecialist111** [comment]
Currently during setup there isn't a way to change the default prompt, however! You can change it yourself. It's located in the coordinator.py. You can adjust this prompt when it's installed from File editor or Studio code. 

![Screenshot_20250115_075555_Chrome](https://github.com/user-attachments/assets/7e96eade-5d0a-4b6e-bd44-70f200b881ae)

**Comment by UlrichThiess** [comment]
This helps me a lot - thank you.

I added 'Alles bitte auf Deutsch." to your SYSTEM_PROMPT. Now the suggestions are in german.

As i changed max_tokens: to 16384 in /homeassistant/.storage/core.config_entries no more answers were truncated.

Thanks again. This is very helpful and funny.

**Comment by ITSpecialist111** [comment]
Awesome thanks for the feedback of course when I started this project I didn't want it to blow through people's wallets so I had some stringent rules that people can change of course :)

Let me know how you get on the next couple of weeks there are some significant changes I would like to make I just need time to sit down and develop

**Comment by UlrichThiess** [comment]
It would be possible to query a few parameters during configuration. For example, a question about the language (text input) in which the response should be given. This configuration input will be added to the SYSTEM_PROMPT as 'Answer in ...'. The tokens can gladly be set to 16,384. The costs will really remain reasonable.

As an alternative to the notification, I created a Markdown card, a helper, and an automation. Now you can press a button, and a new suggestion will be retrieved.

Oh, I just realized that it’s not working. The automation is executed, but no new suggestion appears. ???

### Markdown-Card
```
type: vertical-stack
cards:
  - type: markdown
    content: |-
      ---
      ## <ha-icon icon="mdi:brain"></ha-icon> AI Vorschläge
      ---
  - show_name: false
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: input_button.ai_automation_suggestions
    show_state: false
    icon_height: 100px
  - type: markdown
    content: "{{ state_attr('sensor.ai_automation_suggestions_openai', 'suggestions') }}"
```

### Automation
```
alias: AI Automation Suggestions
description: ""
triggers:
  - trigger: time
    at: "08:00:00"
  - trigger: time
    at: "11:00:00"
  - trigger: time
    at: "14:00:00"
  - trigger: time
    at: "17:00:00"
  - trigger: state
    entity_id:
      - input_button.ai_automation_suggestions
conditions:
  - condition: state
    entity_id: binary_sensor.werktag
    state: "on"
actions:
  - action: ai_automation_suggester.generate_suggestions
    metadata: {}
    data:
      entity_limit: 200
      all_entities: true
mode: single
```

### Helper
![grafik](https://github.com/user-attachments/assets/faa41944-115a-4fec-aa9f-85ea11e98c3b)
